using System.IO;
using Buildalyzer.IO;
using Microsoft.Extensions.Logging;

namespace Buildalyzer.Construction;

/// <summary>The project the .NET SDK generates for a file-based app.</summary>
/// <remarks>
/// The SDK never writes this project to disk - <c>dotnet run app.cs</c> evaluates it in memory at a path
/// that does not exist - but Buildalyzer builds out of process by handing MSBuild a project path on the
/// command line, so the project has to be a real file for the duration of a build. It is written next to
/// the entry point file (the path the SDK would have used) rather than to a temporary directory: the
/// directory is what <c>Directory.Build.props</c>, <c>Directory.Packages.props</c>, <c>nuget.config</c>
/// and <c>global.json</c> discovery walk up from, so moving the project elsewhere would build the app
/// against a different set of imports than <c>dotnet run</c> does.
/// </remarks>
internal sealed class VirtualProject(
    IOPath entryPointFilePath,
    IOPath path,
    string xml,
    string dotnetExePath)
{
    private readonly object _lock = new();

    /// <summary>The number of builds currently relying on the project being on disk.</summary>
    private int _materializations;

    /// <summary>The entry point file (the single <c>.cs</c> file) of the file-based app.</summary>
    public IOPath EntryPointFilePath { get; } = entryPointFilePath;

    /// <summary>The path of the generated project, as chosen by the SDK that generated it.</summary>
    public IOPath Path { get; } = path;

    /// <summary>The generated project XML.</summary>
    public string Xml { get; } = xml;

    /// <summary>The <c>dotnet</c> executable whose SDK generated <see cref="Xml"/>.</summary>
    public string DotnetExePath { get; } = dotnetExePath;

    /// <summary>
    /// Writes the project to disk for the duration of the returned scope, and deletes it again when
    /// the last concurrent scope is disposed.
    /// </summary>
    /// <param name="buildDotnetExePath">The <c>dotnet</c> executable the build is about to run.</param>
    /// <param name="logger">The logger to report a failed write or clean up to.</param>
    public IDisposable Materialize(string buildDotnetExePath, ILogger logger)
    {
        WarnOnGeneratorMismatch(buildDotnetExePath, logger);

        lock (_lock)
        {
            if (_materializations == 0)
            {
                Write();
            }
            _materializations++;
        }

        return new Materialization(this, logger);
    }

    /// <remarks>
    /// The shape of the generated project depends on the SDK that generated it - notably which artifacts
    /// path properties it emits, which the SDK decides by evaluating the project against its own MSBuild
    /// (https://github.com/dotnet/sdk/pull/55970). Generating with one SDK and building with another can
    /// therefore put the app's intermediate output somewhere the SDK never intended. The generation runs
    /// before any <see cref="Environment.BuildEnvironment"/> exists (the project has to be parsed to
    /// decide how to build it), so it uses the default <c>dotnet</c>; a build that was pointed at another
    /// one is the case that cannot be reconciled after the fact.
    /// </remarks>
    private void WarnOnGeneratorMismatch(string buildDotnetExePath, ILogger logger)
    {
        if (!DotnetExePath.IsMatch(buildDotnetExePath))
        {
            logger.LogWarning(
                "The project for file-based app {EntryPoint} was generated by {Generator} but is being built by {Builder}. "
                + "Point EnvironmentOptions.DotnetExePath at the same dotnet executable to build it the way its SDK generated it.",
                EntryPointFilePath,
                DotnetExePath,
                buildDotnetExePath);
        }
    }

    /// <remarks>
    /// A project already at this path is either one an earlier (crashed) analysis left behind, which is
    /// safe to replace, or a real project of the user's, which is not: the generated project carries a
    /// marker that tells the two apart.
    /// </remarks>
    private void Write()
    {
        var file = Path.File()!;

        if (file.Exists && !IsGenerated(file))
        {
            throw new InvalidOperationException(
                $"The file-based app {EntryPointFilePath} cannot be analyzed: its project would be written to {Path}, "
                + "where a project that Buildalyzer did not generate already exists.");
        }

        File.WriteAllText(file.FullName, Xml);
    }

    /// <summary>Returns whether the file at this path is a project Buildalyzer generated.</summary>
    [Pure]
    private static bool IsGenerated(FileInfo file)
    {
        try
        {
            return File.ReadAllText(file.FullName).Contains(FileBasedApp.GeneratedProjectMarker, StringComparison.Ordinal);
        }
        catch (IOException)
        {
            return false;
        }
        catch (UnauthorizedAccessException)
        {
            return false;
        }
    }

    private void Release(ILogger logger)
    {
        lock (_lock)
        {
            _materializations--;
            if (_materializations > 0)
            {
                return;
            }

            try
            {
                Path.File()!.Delete();
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
            {
                // Leaving the project behind is recoverable - the next materialization recognizes it as
                // generated and overwrites it - so a locked or read-only file must not fail the build.
                logger.LogWarning(exception, "Could not delete the generated project {Path}.", Path);
            }
        }
    }

    private sealed class Materialization(VirtualProject project, ILogger logger) : IDisposable
    {
        private bool _disposed;

        public void Dispose()
        {
            if (!_disposed)
            {
                _disposed = true;
                project.Release(logger);
            }
        }
    }
}
